language: node_js
node_js:
  - "12.22.0"

addons:
  chrome: stable

script:
  - npm run build
  - npm run test

after_failure:
  - cat node_modules/@tensorflow-models/speech-commands/package.json.rej
